In [1]:
# To import pandas
import pandas as pd

In [2]:
# To read the dataset
df = pd.read_csv("/content/drive/MyDrive/Messy_Company_Employee_Dataset.csv")

In [3]:
# To display the first 5 rows
df.head()

,Employee_ID,Employee_Name,Department,Job_Title,Age,Gender,Annual_Salary,Experience_Years,Joining_Date,City,Performance_Score,Work_Mode
0,EMP0098,Ananya Nair,NaN,Data Scientist,48.0,Other,108371.0,13.2,2017-06-13,Pune,5.0,Office
1,EMP0046,Faizan Khan,Marketing,Marketing Manager,31.0,Female,108824.0,12.1,2021-09-15,Mumbai,2.0,Office
2,EMP0017,Saira Malik,Human Resources,HR Manager,28.0,Female,119400.0,13.2,2021-02-05,Bengaluru,3.0,Remote
3,EMP0105,Neha Menon,Engineering,Software Engineer,30.0,Female,111847.0,NaN,2018-08-05,Jaipur,4.0,Hybrid
4,EMP0143,Hiba Menon,Sales,Sales Manager,25.0,Female,78677.0,10.9,2018-07-24,Hyderabad,4.0,Hybrid

In [ ]:
# df.head() - displays the top 5 rows of df

In [4]:
# To check the number of rows and columns
df.shape

(157, 12)

In [ ]:
# df.shape dives us the total number of rows and columns in the dataset

In [5]:
# To display the column names
df.columns

Index(['Employee_ID', 'Employee_Name', 'Department', 'Job_Title', 'Age',
       'Gender', 'Annual_Salary', 'Experience_Years', 'Joining_Date', 'City',
       'Performance_Score', 'Work_Mode'],
      dtype='object')

In [6]:
# To check the data types of all columns
df.dtypes

Employee_ID           object
Employee_Name         object
Department            object
Job_Title             object
Age                  float64
Gender                object
Annual_Salary        float64
Experience_Years     float64
Joining_Date          object
City                  object
Performance_Score    float64
Work_Mode             object
dtype: object

In [7]:
# To display the complete information of the dataset
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 157 entries, 0 to 156
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Employee_ID        157 non-null    object
 1   Employee_Name      157 non-null    object
 2   Department         152 non-null    object
 3   Job_Title          157 non-null    object
 4   Age                153 non-null    float64
 5   Gender             152 non-null    object
 6   Annual_Salary      152 non-null    float64
 7   Experience_Years   154 non-null    float64
 8   Joining_Date       157 non-null    object
 9   City               152 non-null    object
 10  Performance_Score  154 non-null    float64
 11  Work_Mode          155 non-null    object
dtypes: float64(4), object(8)
memory usage: 14.8+ KB

In [ ]:
# from this we can identify the number of non-null values and the data type of each column.

In [8]:
# To display the basic statistics of numerical columns
df.describe()

              Age  Annual_Salary  Experience_Years  Performance_Score
count  153.000000     152.000000        154.000000         154.000000
mean    38.130719   89240.592105          8.990909           3.525974
std      9.361661   22626.172309          4.983874           0.930233
min     21.000000   43331.000000          0.600000           2.000000
25%     30.000000   71198.500000          4.450000           3.000000
50%     39.000000   90046.500000          9.350000           4.000000
75%     46.000000  107328.000000         13.200000           4.000000
max     52.000000  162942.000000         17.400000           5.000000

In [ ]:
# this checks the basic statistic information

In [ ]:
# MISSING VALUES

In [9]:
# To check the missing values
df.isnull()

,Employee_ID,Employee_Name,Department,Job_Title,Age,Gender,Annual_Salary,Experience_Years,Joining_Date,City,Performance_Score,Work_Mode
0,False,False,True,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,True,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
152,False,False,False,False,False,False,False,False,False,False,False,False
153,False,False,False,False,False,False,False,False,False,False,False,False
154,False,False,False,False,False,False,False,False,False,False,False,False
155,False,False,False,False,False,False,False,False,False,True,False,False
156,False,False,False,False,False,False,False,False,False,False,False,False

In [10]:
# in the above output where ever there is true it represents Null value, false - Non Null value

In [11]:
# To count the missing values in each column
df.isnull().sum()

Employee_ID          0
Employee_Name        0
Department           5
Job_Title            0
Age                  4
Gender               5
Annual_Salary        5
Experience_Years     3
Joining_Date         0
City                 5
Performance_Score    3
Work_Mode            2
dtype: int64

In [12]:
# To count the total number of missing values
df.isnull().sum().sum()

np.int64(32)

In [13]:
# To calculate the percentage of missing values in each column
missing_percentage = (df.isnull().sum() / len(df)) * 100

In [14]:
display(missing_percentage)

Employee_ID          0.000000
Employee_Name        0.000000
Department           3.184713
Job_Title            0.000000
Age                  2.547771
Gender               3.184713
Annual_Salary        3.184713
Experience_Years     1.910828
Joining_Date         0.000000
City                 3.184713
Performance_Score    1.910828
Work_Mode            1.273885
dtype: float64

In [ ]:
# DUPLICATES

In [15]:
# To check the duplicate rows
df.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
152    False
153    False
154    False
155    False
156     True
Length: 157, dtype: bool

In [16]:
# To count the duplicate rows
df.duplicated().sum()

np.int64(7)

In [17]:
# To display the duplicate rows
df[df.duplicated()]

,Employee_ID,Employee_Name,Department,Job_Title,Age,Gender,Annual_Salary,Experience_Years,Joining_Date,City,Performance_Score,Work_Mode
55,EMP0097,Zoya Shah,Finance,Financial Analyst,41.0,Male,81531.0,4.1,2023-06-05,Mumbai,4.0,Office
61,EMP0075,Manya Joshi,Sales,Sales Manager,29.0,Male,92623.0,11.9,2025-08-17,Jaipur,4.0,Hybrid
100,EMP0139,Simran Sharma,Finance,Accountant,32.0,Female,110617.0,10.3,2021-08-03,Mumbai,3.0,Office
104,EMP0021,Riya Khan,Operations,Operations Executive,49.0,Female,71549.0,4.6,2024-09-20,Chandigarh,3.0,Hybrid
110,EMP0048,Nikhil Dar,Finance,Financial Analyst,27.0,Female,NaN,10.1,2020-06-18,Chandigarh,2.0,Office
139,EMP0150,Nikhil Khan,Finance,Finance Manager,43.0,Male,129905.0,16.3,2018-04-10,Chennai,3.0,Remote
156,EMP0120,Saira Sheikh,Marketing,Marketing Executive,52.0,Male,107328.0,17.4,2020-11-25,Bengaluru,2.0,Remote

In [18]:
# To display the different Department values
df["Department"].value_counts(dropna=False)

Department
Marketing           23
Engineering         21
Customer Success    20
Finance             19
Sales               19
Operations          17
Human Resources     16
Data & Analytics    15
NaN                  5
ENGINEERING          1
engineering          1
Name: count, dtype: int64

In [19]:
# .value_counts(): Counts the total frequency of each unique item.
# dropna=False : Keeps missing values (NaN) in the output list instead of skipping them.

In [20]:
# To display the different Gender values
df["Gender"].value_counts(dropna=False)

Gender
Male      75
Female    68
Other      7
NaN        5
female     1
MALE       1
Name: count, dtype: int64

In [21]:
# To display the different City values
df["City"].value_counts(dropna=False)

City
Chandigarh    24
Pune          23
Jaipur        18
Mumbai        15
Hyderabad     14
Srinagar      13
Bengaluru     12
Delhi         11
Chennai       10
Kolkata        9
NaN            5
delhi          1
DELHI          1
Delhi          1
Name: count, dtype: int64

In [22]:
# To display the different Work Mode values
df["Work_Mode"].value_counts(dropna=False)

Work_Mode
Remote    56
Hybrid    50
Office    47
NaN        2
REMOTE     1
remote     1
Name: count, dtype: int64

In [24]:
# To store the original number of rows and columns
before_shape = df.shape
before_shape

(157, 12)

In [25]:
# To store the original number of missing values
before_missing = df.isnull().sum().sum()
before_missing

np.int64(32)

In [26]:
# To store the original number of duplicate rows
before_duplicates = df.duplicated().sum()
before_duplicates

np.int64(7)

In [27]:
# To remove extra spaces from Gender values
df["Gender"] = df["Gender"].str.strip()

In [28]:
# To standardize Gender values
df["Gender"] = df["Gender"].str.title()

In [29]:
# To display the Gender values
df["Gender"].value_counts(dropna=False)

Gender
Male      76
Female    69
Other      7
NaN        5
Name: count, dtype: int64

In [30]:
# To standardize City values
df["City"] = df["City"].replace({
    "delhi": "Delhi",
    "DELHI": "Delhi"
})

In [31]:
# To convert Joining Date into datetime format
df["Joining_Date"] = pd.to_datetime(df["Joining_Date"], errors="coerce")

In [ ]:
# errors="coerce": Replaces invalid or broken date entries with NaN / NaT

In [32]:
# To check the Joining Date data type
df["Joining_Date"].dtype

dtype('<M8[ns]')

In [33]:
# To remove duplicate rows
df = df.drop_duplicates()

# To check the number of rows after removing duplicates
df.shape

(150, 12)

In [ ]:
# From shape we come to know before there were 157 rows , now they became 150, 7 rows were removed

In [34]:
# To check the missing values after removing duplicates
df.isnull().sum()

Employee_ID          0
Employee_Name        0
Department           5
Job_Title            0
Age                  4
Gender               5
Annual_Salary        4
Experience_Years     3
Joining_Date         0
City                 5
Performance_Score    3
Work_Mode            2
dtype: int64

In [35]:
df.isnull().sum().sum()

np.int64(31)

In [36]:
# To calculate the median Age
df["Age"].median()

39.0

In [ ]:
# we already know median = mid value

In [37]:
# To fill missing Age values with the median
df["Age"] = df["Age"].fillna(df["Age"].median())

# To check missing Age values
df["Age"].isnull().sum()

np.int64(0)

In [ ]:
# here we filed all missing values with median of age column

In [38]:
# To calculate the median Annual Salary
df["Annual_Salary"].median()

89302.0

In [39]:
# To fill missing Annual Salary values with the median
df["Annual_Salary"] = df["Annual_Salary"].fillna(df["Annual_Salary"].median())

# To check missing Annual Salary values
df["Annual_Salary"].isnull().sum()

np.int64(0)

In [40]:
# To calculate the median Experience
df["Experience_Years"].median()

9.2

In [41]:
# To fill missing Experience values with the median
df["Experience_Years"] = df["Experience_Years"].fillna(df["Experience_Years"].median())

# To check missing Experience values
df["Experience_Years"].isnull().sum()

np.int64(0)

In [42]:
# To calculate the median Performance Score
df["Performance_Score"].median()

4.0

In [43]:
# To fill missing Performance Score values with the median
df["Performance_Score"] = df["Performance_Score"].fillna(df["Performance_Score"].median())

# To check missing Performance Score values
df["Performance_Score"].isnull().sum()

np.int64(0)

In [44]:
# To calculate the mode of Department
df["Department"].mode()

0    Marketing
Name: Department, dtype: object

In [45]:
# To fill missing Department values with the mode
df["Department"] = df["Department"].fillna(df["Department"].mode()[0])

# To check missing Department values
df["Department"].isnull().sum()

np.int64(0)

In [46]:
# To calculate the mode of Gender
df["Gender"].mode()

0    Male
Name: Gender, dtype: object

In [47]:
# To fill missing Gender values with the mode
df["Gender"] = df["Gender"].fillna(df["Gender"].mode()[0])

# To check missing Gender values
df["Gender"].isnull().sum()

np.int64(0)

In [48]:
# To calculate the mode of Work Mode
df["Work_Mode"].mode()

0    Remote
Name: Work_Mode, dtype: object

In [49]:
# To fill missing Work Mode values with the mode
df["Work_Mode"] = df["Work_Mode"].fillna(df["Work_Mode"].mode()[0])

# To check missing Work Mode values
df["Work_Mode"].isnull().sum()

np.int64(0)

In [50]:
# To check all remaining missing values
df.isnull().sum()

Employee_ID          0
Employee_Name        0
Department           0
Job_Title            0
Age                  0
Gender               0
Annual_Salary        0
Experience_Years     0
Joining_Date         0
City                 5
Performance_Score    0
Work_Mode            0
dtype: int64

In [51]:
# To calculate the mode of City
df["City"].mode()

0    Pune
Name: City, dtype: object

In [52]:
# To fill missing City values with the mode
df["City"] = df["City"].fillna(df["City"].mode()[0])

# To check missing City values
df["City"].isnull().sum()

np.int64(0)

In [53]:
# To check all remaining missing values
df.isnull().sum()

Employee_ID          0
Employee_Name        0
Department           0
Job_Title            0
Age                  0
Gender               0
Annual_Salary        0
Experience_Years     0
Joining_Date         0
City                 0
Performance_Score    0
Work_Mode            0
dtype: int64

In [54]:
# To count the total remaining missing values
df.isnull().sum().sum()

np.int64(0)

In [55]:
# To check the data types after cleaning
df.dtypes

Employee_ID                  object
Employee_Name                object
Department                   object
Job_Title                    object
Age                         float64
Gender                       object
Annual_Salary               float64
Experience_Years            float64
Joining_Date         datetime64[ns]
City                         object
Performance_Score           float64
Work_Mode                    object
dtype: object

In [56]:
# To count duplicate rows after cleaning
df.duplicated().sum()

np.int64(0)

In [57]:
# To check the final number of rows and columns
df.shape

(150, 12)

In [58]:
# To display the cleaned dataset
df.head(10)

,Employee_ID,Employee_Name,Department,Job_Title,Age,Gender,Annual_Salary,Experience_Years,Joining_Date,City,Performance_Score,Work_Mode
0,EMP0098,Ananya Nair,Marketing,Data Scientist,48.0,Other,108371.0,13.2,2017-06-13,Pune,5.0,Office
1,EMP0046,Faizan Khan,Marketing,Marketing Manager,31.0,Female,108824.0,12.1,2021-09-15,Mumbai,2.0,Office
2,EMP0017,Saira Malik,Human Resources,HR Manager,28.0,Female,119400.0,13.2,2021-02-05,Bengaluru,3.0,Remote
3,EMP0105,Neha Menon,Engineering,Software Engineer,30.0,Female,111847.0,9.2,2018-08-05,Jaipur,4.0,Hybrid
4,EMP0143,Hiba Menon,Sales,Sales Manager,25.0,Female,78677.0,10.9,2018-07-24,Hyderabad,4.0,Hybrid
5,EMP0117,Zoya Kapoor,Finance,Finance Manager,42.0,Male,128567.0,15.4,2017-08-02,Chennai,4.0,Hybrid
6,EMP0081,Maryam Mir,Marketing,Content Strategist,37.0,Male,58878.0,1.8,2024-01-18,Pune,2.0,Office
7,EMP0026,Omar Das,Engineering,QA Engineer,38.0,Male,112276.0,12.0,2019-05-14,Chandigarh,4.0,Hybrid
8,EMP0129,Dev Ahmed,Data & Analytics,Data Scientist,45.0,Male,135730.0,14.1,2021-01-27,Srinagar,2.0,Remote
9,EMP0121,Karan Patel,Data & Analytics,BI Analyst,40.0,Female,101886.0,8.5,2020-06-28,Chennai,4.0,Remote

In [60]:
# To store the final number of rows and columns
after_shape = df.shape
after_shape

(150, 12)

In [61]:
# To store the final number of missing values
after_missing = df.isnull().sum().sum()
after_missing

np.int64(0)

In [62]:
# To store the final number of duplicate rows
after_duplicates = df.duplicated().sum()
after_duplicates

np.int64(0)

In [63]:
# To display the before and after cleaning comparison
comparison = pd.DataFrame({
    "Before Cleaning": [
        before_shape[0],
        before_shape[1],
        before_missing,
        before_duplicates
    ],
    "After Cleaning": [
        after_shape[0],
        after_shape[1],
        after_missing,
        after_duplicates
    ]
}, index=[
    "Rows",
    "Columns",
    "Missing Values",
    "Duplicate Rows"
])

comparison

                Before Cleaning  After Cleaning
Rows                        157             150
Columns                      12              12
Missing Values               32               0
Duplicate Rows                7               0

In [ ]:
# AFTER CLEANING

In [64]:
# To display the final dataset information
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 150 entries, 0 to 155
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Employee_ID        150 non-null    object
 1   Employee_Name      150 non-null    object
 2   Department         150 non-null    object
 3   Job_Title          150 non-null    object
 4   Age                150 non-null    float64
 5   Gender             150 non-null    object
 6   Annual_Salary      150 non-null    float64
 7   Experience_Years   150 non-null    float64
 8   Joining_Date       150 non-null    datetime64[ns]
 9   City               150 non-null    object
 10  Performance_Score  150 non-null    float64
 11  Work_Mode          150 non-null    object
dtypes: datetime64[ns](1), float64(4), object(7)
memory usage: 15.2+ KB

In [65]:
# To display the final missing value count
df.isnull().sum()

Employee_ID          0
Employee_Name        0
Department           0
Job_Title            0
Age                  0
Gender               0
Annual_Salary        0
Experience_Years     0
Joining_Date         0
City                 0
Performance_Score    0
Work_Mode            0
dtype: int64

In [66]:
# To display the final duplicate count
df.duplicated().sum()

np.int64(0)

In [67]:
# To export the cleaned dataset as a CSV file
df.to_csv("/content/drive/MyDrive/Cleaned_Company_Employee_Dataset.csv", index=False)

In [68]:
# To read the cleaned CSV file
cleaned_df = pd.read_csv("/content/drive/MyDrive/Cleaned_Company_Employee_Dataset.csv")

In [69]:
# To display the first 5 rows of the cleaned file
cleaned_df.head()

,Employee_ID,Employee_Name,Department,Job_Title,Age,Gender,Annual_Salary,Experience_Years,Joining_Date,City,Performance_Score,Work_Mode
0,EMP0098,Ananya Nair,Marketing,Data Scientist,48.0,Other,108371.0,13.2,2017-06-13,Pune,5.0,Office
1,EMP0046,Faizan Khan,Marketing,Marketing Manager,31.0,Female,108824.0,12.1,2021-09-15,Mumbai,2.0,Office
2,EMP0017,Saira Malik,Human Resources,HR Manager,28.0,Female,119400.0,13.2,2021-02-05,Bengaluru,3.0,Remote
3,EMP0105,Neha Menon,Engineering,Software Engineer,30.0,Female,111847.0,9.2,2018-08-05,Jaipur,4.0,Hybrid
4,EMP0143,Hiba Menon,Sales,Sales Manager,25.0,Female,78677.0,10.9,2018-07-24,Hyderabad,4.0,Hybrid

In [70]:
# To check the shape of the exported dataset
cleaned_df.shape

(150, 12)

In [71]:
# To check missing values in the exported dataset
cleaned_df.isnull().sum().sum()

np.int64(0)

In [72]:
# To check duplicate rows in the exported dataset
cleaned_df.duplicated().sum()

np.int64(0)

In [ ]:
"""
1. The dataset initially contained 157 rows and 12 columns.

2. A total of 32 missing values were identified across different columns.

3. A total of 7 duplicate records were identified and removed using drop_duplicates().

4. Missing numerical values in Age, Annual_Salary, Experience_Years, and Performance_Score were handled using median imputation.

5. Missing categorical values in Department, Gender, City, and Work_Mode were handled using mode imputation.

6. Inconsistent entries in Department, Gender, City, and Work_Mode were standardized.

7. The Joining_Date column was converted from object data type to datetime format.

8. After cleaning, the dataset contained 150 rows and 12 columns.

9. After cleaning, the dataset contained 0 missing values and 0 duplicate records.

10. The cleaned dataset was exported as Cleaned_Company_Employee_Dataset.csv and is ready for further analysis.
"""